// Add/edit as many as you want.
window.AFFIRMATIONS = [
  "I am allowed to start messy.",
  "My pace is still progress.",
  "I don’t need permission to evolve.",
  "Today I choose clarity over chaos.",
  "I can be nervous and still be powerful.",
  "What’s for me won’t miss me.",
  "I trust my taste. It’s guiding me.",
  "Small steps still move mountains.",
  "My work deserves to be seen.",
  "I finish what I start—one step at a time.",
  "I’m building something real.",
  "I am becoming undeniable.",
  "Direction over distraction.",
  "I am safe to be visible.",
  "I release perfection and keep the promise.",
  "I create even when it’s quiet.",
  "I choose discipline, not pressure.",
  "I can reset and still win today.",
  "I’m aligned with what’s next.",
  "I don’t chase—I attract.",

  "I am worthy of rest.",
  "Progress, not perfection, is the goal.",
  "My feelings are valid, even if others don't understand them.",
  "I release the need to control the outcome.",
  "I choose joy right now.",
  "I have everything I need within me.",
  "My voice matters and deserves to be heard.",
  "Done is better than perfect.",
  "I am strong enough to handle what comes my way.",
  "I forgive myself for past mistakes.",
  "I set boundaries that protect my peace.",
  "I embrace change as an opportunity for growth.",
  "My intuition is a reliable guide.",
  "I deserve happiness and success.",
  "I trust the timing of my life.",
  "I am present in this moment.",
  "My imperfections make me unique and valuable.",
  "I release judgment of myself and others.",
  "I take inspired action toward my dreams.",
  "It's okay to ask for help.",
  "I choose faith over fear.",
  "My energy is a precious resource.",
  "I am open to receiving good things.",
  "I honor my commitments to myself.",
  "Mistakes are lessons that guide me forward.",
  "I am enough, exactly as I am right now.",
  "I breathe deeply and release tension.",
  "I create my own opportunities.",
  "I speak to myself with kindness and respect.",
  "I focus on what I can control.",
  "My creativity flows effortlessly.",
  "I am grateful for this moment.",
  "My past does not define my future.",
  "I choose to see the good in others.",
  "I celebrate my small wins.",
  "I am a magnet for positive experiences.",
  "I can handle discomfort and uncertainty.",
  "I nourish my body with healthy choices.",
  "I am not my thoughts.",
  "I trust the process.",
  "I listen to understand, not just to reply.",
  "I make time for what truly matters.",
  "I am constantly evolving and improving.",
  "My worth is inherent and unconditional.",
  "I speak my truth with kindness.",
  "I have the strength to let go.",
  "I honor my unique pace and timing.",
  "My focus creates my reality.",
  "I treat myself like someone I love.",
  "I choose to see challenges as opportunities.",

  "You matter more than you realize — and today, you’re appreciated.",
  "Someone thought of you when this cookie was made.",
  "You are seen, even in the moments you feel overlooked.",
  "Your presence adds value here.",
  "You don’t have to earn belonging — you already have it.",
  "Today is better because you showed up.",
  "Your effort does not go unnoticed.",
  "You bring something no one else can.",
  "This moment is a small thank-you, just for you.",
  "You are allowed to feel proud of yourself.",
  "You deserve moments of sweetness.",
  "You are valued beyond productivity.",
  "You are appreciated today — not someday.",
  "This cookie exists because you matter."
];
