// Add/edit as many as you want.
window.AFFIRMATIONS = [
  "I am allowed to start messy.",
  "My pace is still progress.",
  "I don’t need permission to evolve.",
  "Today I choose clarity over chaos.",
  "I can be nervous and still be powerful.",
  "What’s for me won’t miss me.",
  "I trust my taste. It’s guiding me.",
  "Small steps still move mountains.",
  "My work deserves to be seen.",
  "I finish what I start—one step at a time.",
  "I am becoming undeniable.",
  "Direction over distraction.",
  "I am safe to be visible.",
  "I release perfection and keep the promise.",
  "I create even when it’s quiet.",
  "I’m building something real.",
  "I choose discipline, not pressure.",
  "I can reset and still win today.",
  "I’m aligned with what’s next.",
  "I don’t chase—I attract."
  "I am worthy of rest."
"Progress, not perfection, is the goal."
"My feelings are valid, even if others don't understand them."
"I release the need to control the outcome."
"I choose joy right now."
"I have everything I need within me."
"My voice matters and deserves to be heard."
"Done is better than perfect."
"I am strong enough to handle what comes my way."
"I forgive myself for past mistakes."
"I set boundaries that protect my peace."
"I embrace change as an opportunity for growth."
"My intuition is a reliable guide."
"I deserve happiness and success."
"I trust the timing of my life."
"I am present in this moment."
"My imperfections make me unique and valuable."
"I release judgment of myself and others."
"I take inspired action toward my dreams."
"It's okay to ask for help."
"I choose faith over fear."
"My energy is a precious resource."
"I am open to receiving good things."
"I honor my commitments to myself."
"Mistakes are lessons that guide me forward."
"I am enough, exactly as I am right now."
"I breathe deeply and release tension."
"I create my own opportunities."
"I speak to myself with kindness and respect."
"I focus on what I can control."
"My creativity flows effortlessly."
"I am grateful for this moment."
"My past does not define my future."
"I choose to see the good in others."
"I celebrate my small wins."
"I am a magnet for positive experiences."
"I can handle discomfort and uncertainty."
"I nourish my body with healthy choices."
"I am not my thoughts."
"I trust the process."
"I listen to understand, not just to reply."
"I make time for what truly matters."
"I am constantly evolving and improving."
"My worth is inherent and unconditional."
"I speak my truth with kindness."
"I have the strength to let go."
"I honor my unique pace and timing."
"My focus creates my reality."
"I treat myself like someone I love."
"I choose to see challenges as opportunities."
"You matter more than you realize — and today, you’re appreciated."
"Someone thought of you when this cookie was made."
"You are seen, even in the moments you feel overlooked."
"Your presence adds value here."
"You don’t have to earn belonging — you already have it."
"Today is better because you showed up."
"You are an important part of something bigger."
"Your effort does not go unnoticed."
"You bring something no one else can."
"This moment is a small thank-you, just for you."
"You are allowed to feel proud of yourself."
"Even on quiet days, your contribution matters."
"You are appreciated exactly as you are."
"You make a difference by being you."
"You deserve kindness — including from yourself."
"You belong here."
"You are valued more than words can say."
"Your work, care, and energy are felt."
"You are worthy of being celebrated."
"Someone is grateful for you today."
"You are not invisible."
"You are allowed to slow down."
"Your heart shows in what you do."
"You are enough — right now."
"You add meaning to ordinary moments."
"You are doing better than you think."
"You deserve moments of sweetness."
"Your presence is appreciated."
"You are part of what makes this work."
"You matter to this story."
"You don’t need to prove your worth."
"You are respected here."
"Your voice matters."
"You are allowed to receive."
"You bring warmth wherever you go."
"You are valued beyond productivity."
"Your effort is felt, even when it’s quiet."
"You are not forgotten."
"You are appreciated today — not someday."
"You make things better by being here."
"You deserve recognition."
"You are trusted."
"You are supported more than you know."
"Your contribution counts."
"You are allowed to take up space."
"You belong exactly where you are."
"You are part of something meaningful."
"Your care makes a difference."
"You are worthy of appreciation."
"You are doing important work."
"You are not just another name."
"You are valued for who you are."
"Your presence matters."
"You deserve moments of joy."
"You are appreciated today."
"You are seen — truly."
"You make an impact, even in small ways."
"You are allowed to feel proud."
"You are part of what makes this special."
"You are cared about."
"You bring heart into what you do."
"You are important to this community."
"You deserve to be acknowledged."
"You are valued beyond results."
"You are appreciated for showing up."
"You matter — full stop."
"You are worthy of kindness."
"You are an essential part of this."
"You are doing meaningful work."
"You belong here, just as you are."
"You are more than what you produce."
"You are appreciated today, not just on special occasions."
"You bring balance and care."
"You are seen in ways you may not notice."
"You deserve this moment of sweetness."
"You are valued for your effort and your heart."
"You make a difference by being present."
"You are part of what makes this place feel human."
"You are appreciated for who you are."
"You matter more than metrics."
"You are recognized."
"You bring something unique."
"You are not overlooked."
"You are worthy of appreciation without conditions."
"You are important to this team, this moment, this work."
"You are allowed to feel appreciated."
"You add meaning to the everyday."
"You are seen and valued."
"You are deserving of gratitude."
"You matter — even on ordinary days."
"You are part of what makes this work."
"You are appreciated more than you know."
"You are allowed to receive this."
"You are valued beyond titles."
"You are noticed."
"You bring care into the world."
"You are worthy of recognition."
"You are seen, respected, and appreciated."
"You are an important part of this moment."
"This cookie exists because you matter."
"I am allowed to start messy."
"My pace is still progress."
"I don’t need permission to evolve."
"Today I choose clarity over chaos."
"I can be nervous and still be powerful."
"What’s for me won’t miss me."
"I trust my taste. It’s guiding me."
"I finish what I start—one step at a time."
"I’m building something real."
"I am becoming undeniable."
"I create even when it’s quiet."
"I let go of perfection and keep the promise."
"My work deserves to be seen."
"I’m aligned with what’s next."
"Small actions create big outcomes."
"I am disciplined, not pressured."
"I choose direction over distraction."
"I am safe to be visible."
"I don’t chase—I attract."
"I’m proud of my effort today."  
];
